name: deploy_private
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - run: pm2 stop 0
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_NODE_ENV: "production"
          ENV_RUN_MODE: "fork"
          ENV_PROTOCOL: http
          ENV_HOST: localhost
          ENV_PORT: 8080
          ENV_SECRET_STRING: "ADLVFEyWItdkAi9V1KPt"
          ENV_TIME_SESSION: 60
          ENV_DB_MODE: "mongoDB"
          ENV_MONGOOSE_URI: "mongodb://simcompras:simpass@192.168.0.3:27017/simcompras"          
      - run: pm2 start 0
      - run: npm run build --if-present
      - run: npm run test --if-present