name: deploy_private
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_NODE_ENV: "production"
          ENV_RUN_MODE: "fork"
          ENV_PROTOCOL: http
          ENV_HOST: ${{ secrets.HOST }}
          ENV_PORT: ${{ secrets.PORT }}
          ENV_SECRET_STRING: ${{ secrets.SECRET_STRING }}
          ENV_TIME_SESSION: 60
          ENV_DB_MODE: "mongoDB"
          ENV_MONGOOSE_URI: ${{ secrets.MONGOOSE_URI }}  
      - run: npm run build --if-present
      - run: npm run test --if-present