name: deploy_private
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Create .env file
        run: |
          touch .env
          echo NODE_ENV=production >> .env
          echo MODE=fork >> .env
          echo PROTOCOL=http >> .env
          echo HOST=${{ secrets.HOST }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo SECRET_STRING=${{ secrets.SECRET_STRING }} >> .env
          echo TIME_SESSION=60 >> .env
          echo DB_MODE=mongoDB >> .env
          echo MONGOOSE_URI=${{ secrets.MONGOOSE_URI }} >> .env
          cat .env
      - run: npm run build --if-present
      - run: npm run test --if-present
